name: Test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Check formatting
        run: |
          files=$(go run golang.org/x/tools/cmd/goimports -l -local "github.com/G-Research" .)
          if [[ $files != "" ]]; then
            echo "Files need goimports running on them:"
            echo "$files"
            exit 1
          fi

      - name: Run tests
        run: |
          go test ./...
